name: CI

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
#    - uses: actions/checkout@v1
    
#    - name: Run a multi-line script
#      run: fsutil volume diskfree 'c:'


    - name: script
      run: |
        sudo ls /dev/disk/by-id/
        sudo cat /var/cache/debconf/config.dat
        sudo dpkg-reconfigure grub-efi-amd64-signed
